### ISSUE TITLE
Example not working, no docs available

### ISSUE THREAD

**Issue by antitoxic** [ashima/pdf-table-extract#14]
I'm trying to set things up so I can convert pdfs to tables.

I'm using fedora 20 and i have run:

``` sh
python setup.py install
pip install pandas
```

Both packages pdftoppm and pdftotext are installed. 

Running this :

``` sh
cd example
python test_to_pandas.py
```

fails with 

``` sh
Traceback (most recent call last):
  File "test_to_pandas.py", line 5, in <module>
    cells = [pdf.process_page("a.pdf",p) for p in pages]
  File "/usr/lib/python2.7/site-packages/pdf_table_extract-0.1-py2.7.egg/pdftableextract/core.py", line 89, in process_page
    (maxval, width, height, data) = readPNM(p.stdout)
  File "/usr/lib/python2.7/site-packages/pdf_table_extract-0.1-py2.7.egg/pdftableextract/pnm.py", line 24, in readPNM
    raise IOError("Expected 2 elements from parsing PNM file, got {0}: {1}".format(ls, name))
IOError: Expected 2 elements from parsing PNM file, got 0: <pipe>
```

PS: I've renamed the pdf from `example.podf` to `a.pdf`

**Comment by jonathan-s** [comment]
I'm confirming the problem, I just tried this out.

**Comment by ekta1007** [comment]
Here's what I did to resolve this on Mac(Yosemite) (in that order) 

```
sudo port install xorg-libXt +flat_namespace
sudo port install openmotif 
sudo port install xpm
sudo port install xpdf
sudo port install poppler
```

after this re-ran the example code-worked perfectly .
