### ISSUE TITLE
IndexError when last page is blank

### ISSUE THREAD

**Issue by jonathan-s** [ashima/pdf-table-extract#15]
If the last page is completely blank an index error occurs. 

```
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File "scrape_pdf2.py", line 159, in test
    pdflist = get_table_pages(pages)
  File "scrape_pdf2.py", line 95, in get_table_pages
    cells = [pdf.process_page("example.pdf",p) for p in pages]
  File "/Users/jonathan/.virtualenvs/elance/lib/python2.7/site-packages/pdf_table_extract-0.1-py2.7.egg/pdftableextract/core.py", line 211, in process_page
    if vd[i+1]-vd[i] > maxdiv :
IndexError: index out of bounds
```

**Comment by eelsirhc** [comment]
I'm not really sure what you want to happen. There is a page, so an IOError seems wrong. The code should raise an explicit error rather than fail by assuming that `vd` exists, but if there was no table on that page what behavior are you expecting?

**Comment by jonathan-s** [comment]
I think an option for failing silently would be nice, that is if it fails it would just skip that page.
