### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by predicador37** [ashima/pdf-table-extract#19]
Hi: 
I'm trying to use pdf-table-extract with a slightly different pdf table, but its first column is entirely treated as a header cell. Where can I find more documentation about process_page()? Some parameter description, examples... anything would be welcome. 
Thanks in advance

**Comment by PrashantMangale** [comment]
Hello Ma'aM, Im Prashant. I want to use your library to convert PDF to CSV foramt. But I'm not familier with Python, so can u tell steps to use your library for conversion? 
Or can u provide me some simple documentation to execute which file for PDF conversion.
Its a good for me. 
Give me a valuable feedback.
Thanks in advance.

**Comment by thapakazi** [comment]
hell ya, how to use such awesome thing :worried: 
![head-mouse](https://cloud.githubusercontent.com/assets/1695906/11917671/b736217a-a738-11e5-8908-cd15d4ededd1.gif)

please spare us with at least one line command line example.

**Comment by hammansamuel** [comment]
Here's the steps I followed, in order to get the example working (in the `example` folder).
1. Download the code as zip and extract
2. Install _pdftableextract_ using `python setup.py install`, from the main folder
3. Install the _pandas_ dependency using `pip install pandas` (from their [website](http://pandas.pydata.org/), pandas is an open source, BSD-licensed library providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language)
4. Run the example code using `python test_to_pandas.py`. This extracts the table in the pdf file and shows you the output on the command prompt (can use stdout to save to a file too, e.g. `python test_to_pandas.py > extracted_table.txt`)

The example shows the library does a pretty good job of extracting the table from the example pdf file. Look at the example Python script provided for the specific commands used

**Comment by atinder** [comment]
I got the error for pdftoppm while following @hwsamuel 
fixed it with `brew install poppler ` on my mac

**Comment by indiranell** [comment]
I am getting the below error:

Traceback (most recent call last):
  File "test_to_pandas.py", line 5, in <module>
    cells = [pdf.process_page("example.pdf",p) for p in pages]
  File "C:\Python27\lib\site-packages\pdftableextract\core.py", line 79, in process_page
    check_for_required_executable("pdftoppm",["pdftoppm","-h"])
  File "C:\Python27\lib\site-packages\pdftableextract\core.py", line 24, in check_for_required_executable
    raise OSError(message)
OSError: Error running pdftoppm.
Command failed: pdftoppm -h
[Error 2] The system cannot find the file specified

Can someone tell what this error means?

**Comment by vishnu41** [comment]
@indiranell  I have same problem. Any updates?

**Comment by ghost** [comment]
I am also facing similar error, could someone help.

OSError: Error running pdftoppm.
Command failed: pdftoppm -h
[Error 2] The system cannot find the file specified
